apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "opl.openshiftpartnerlabs.com/v1alpha1",
          "kind": "ClusterRequest",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "opl-cluster-operator"
            },
            "name": "dev-cluster-02",
            "namespace": "default"
          },
          "spec": {
            "baseDomain": "openshiftpartnerlabs.com",
            "cloudProvider": "aws",
            "clusterName": "dev-cluster-02",
            "clusterSize": "medium",
            "companyName": "Example Corp",
            "environment": "development",
            "labId": 123,
            "networking": {
              "clusterNetworkCIDR": "10.128.0.0/14",
              "machineNetworkCIDR": "10.0.0.0/16",
              "serviceNetworkCIDR": "172.30.0.0/16"
            },
            "openshiftVersion": "img4.20.10-x86-64-appsub",
            "region": "na1",
            "requestType": "engineering",
            "requestedBy": "user@example.com"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-02-05T17:00:56Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: opl-cluster-operator.v0.2.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterRequest is the Schema for the clusterrequests API.
      displayName: Cluster Request
      kind: ClusterRequest
      name: clusterrequests.opl.openshiftpartnerlabs.com
      version: v1alpha1
  description: OpenShift Partner Labs Cluster Provisioning Operator
  displayName: OPL Cluster Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          - secrets
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - opl.openshiftpartnerlabs.com
          resources:
          - clusterrequests
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - opl.openshiftpartnerlabs.com
          resources:
          - clusterrequests/finalizers
          verbs:
          - update
        - apiGroups:
          - opl.openshiftpartnerlabs.com
          resources:
          - clusterrequests/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: opl-cluster-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: opl-cluster-operator
          control-plane: controller-manager
        name: opl-cluster-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: opl-cluster-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: opl-cluster-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                env:
                - name: GIT_REPO_URL
                  value: git@github.com:yashoza19/opl-argocd.git
                - name: GIT_BRANCH
                  value: master
                - name: GIT_SSH_KEY_PATH
                  value: /etc/git-secret/id_rsa
                - name: GIT_LOCAL_PATH
                  value: /tmp/opl-argocd
                - name: GIT_AUTHOR_NAME
                  value: OPL Cluster Operator
                - name: GIT_AUTHOR_EMAIL
                  value: cluster-operator@openshiftpartnerlabs.com
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: partnerlabs-datastore-pguser-labrat
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      key: port
                      name: partnerlabs-datastore-pguser-labrat
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: DB_NAME
                      name: opl-cluster-operator-database-sync-config
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: user
                      name: partnerlabs-datastore-pguser-labrat
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: partnerlabs-datastore-pguser-labrat
                - name: DB_SSL_MODE
                  valueFrom:
                    configMapKeyRef:
                      key: DB_SSL_MODE
                      name: opl-cluster-operator-database-sync-config
                - name: DB_MAX_CONNS
                  valueFrom:
                    configMapKeyRef:
                      key: DB_MAX_CONNS
                      name: opl-cluster-operator-database-sync-config
                - name: DB_MIN_CONNS
                  valueFrom:
                    configMapKeyRef:
                      key: DB_MIN_CONNS
                      name: opl-cluster-operator-database-sync-config
                - name: SYNC_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: SYNC_NAMESPACE
                      name: opl-cluster-operator-database-sync-config
                - name: SYNC_POLLING_INTERVAL
                  valueFrom:
                    configMapKeyRef:
                      key: SYNC_POLLING_INTERVAL
                      name: opl-cluster-operator-database-sync-config
                - name: SYNC_BATCH_SIZE
                  valueFrom:
                    configMapKeyRef:
                      key: SYNC_BATCH_SIZE
                      name: opl-cluster-operator-database-sync-config
                - name: BASE_DOMAIN
                  valueFrom:
                    configMapKeyRef:
                      key: BASE_DOMAIN
                      name: opl-cluster-operator-database-sync-config
                image: quay.io/yoza/opl-cluster-operator:v0.2.3
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /etc/git-secret
                  name: git-ssh-key
                  readOnly: true
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: opl-cluster-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: git-ssh-key
                secret:
                  defaultMode: 420
                  secretName: git-ssh-key
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: opl-cluster-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - cluster
  - provisioning
  - hive
  links:
  - name: Opl Cluster Operator
    url: https://opl-cluster-operator.domain
  maintainers:
  - email: your-email@domain.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: OpenShift Partner Labs
  version: 0.2.3
