apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opl-cluster-operator
  name: opl-cluster-operator-clusterrequest-admin-role
rules:
- apiGroups:
  - opl.openshiftpartnerlabs.com
  resources:
  - clusterrequests
  verbs:
  - '*'
- apiGroups:
  - opl.openshiftpartnerlabs.com
  resources:
  - clusterrequests/status
  verbs:
  - get
